FROM golang:1.19-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /go_server

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /go_server /go_server

EXPOSE 8080

USER nonroot:nonroot

ENV GIN_MODE release

ENTRYPOINT ["/go_server"]