variable "repo_name" {
  type    = string
  default = "course-devops-terraform-generated"
}

variable "repo_owner" {
  type    = string
  default = "whutao"
}

variable "repo_description" {
  type    = string
  default = "The repository generated by Terraform"
}

variable "repo_default_branch_name" {
  type    = string
  default = "master"
}

variable "repo_visibility" {
  type    = string
  default = "public"
}

variable "repo_license" {
  type    = string
  default = "mit"
}

variable "repo_gitignore" {
  type    = string
  default = "VisualStudio"
}
