{
 "title": "fastApi",
 "description": "fastApi的玩意",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "200 http_requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(http_requests_total{instance=~\".+\",status=\"2xx\"}[10m])",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "not 200 http_requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(http_requests_total{handler!=\"none\",status!=\"2xx\"}[10m])",
     "legendFormat": "{{method}} {{handler}} {{status}}"
    }
   ]
  },
  {
   "title": "python_gc_objects_collected",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "abs(idelta(python_gc_objects_collected_total{job=\"fastApi\"}[1h]))",
     "legendFormat": "generation{{generation}}"
    }
   ]
  },
  {
   "title": "python_gc_objects_uncollectable",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "abs(idelta(python_gc_objects_uncollectable_total{job=\"fastApi\"}[1h]))",
     "legendFormat": "generation{{generation}}"
    }
   ]
  },
  {
   "title": "python_gc_collections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "abs(idelta(python_gc_collections_total{job=\"fastApi\"}[1h]))",
     "legendFormat": "generation{{generation}}"
    }
   ]
  },
  {
   "title": "接口每分钟响应时间平均延时",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "idelta(http_request_duration_seconds_sum{job=\"fastApi\",handler!=\"none\"}[1m])/idelta(http_request_duration_seconds_count{job=\"fastApi\",handler!=\"none\"}[1m])",
     "legendFormat": "{{instance}} {{handler}}"
    }
   ]
  }
 ]
}