{
 "title": "Rocket web application dashboard",
 "description": "Dashboard for monitoring Rocket webapps using rocket_prometheus exporter (derived from flask dashboard example)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rocket_http_requests_duration_seconds_count{status=\"200\"}[30s])",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rocket_http_requests_duration_seconds_count{status!=\"200\"}[30s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(rocket_http_requests_total[1m])",
     "legendFormat": "HTTP {{ status }} {{ endpoint }}"
    }
   ]
  },
  {
   "title": "Average response time [30s]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(rocket_http_requests_duration_seconds_sum{status=\"200\"}[30s])\n/\nrate(rocket_http_requests_duration_seconds_count{status=\"200\"}[30s])",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(rocket_http_requests_duration_seconds_bucket{status=\"200\"}[30s]))",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Requests under 250ms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(rocket_http_requests_duration_seconds_bucket{status=\"200\",le=\"0.25\"}[30s]) \n/ ignoring (le) increase(rocket_http_requests_duration_seconds_count{status=\"200\"}[30s])",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(rocket_http_requests_duration_seconds_bucket{status=\"200\"}[30s]))",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  }
 ]
}